import type { LoteriaDeckDefinition } from "./loteriaTypes";

export const LOTERIA_TRADICIONAL_DECK: LoteriaDeckDefinition = {
  id: "deck-tradicional",
  slug: "tradicional",
  name: "Lotería Mexicana Tradicional",
  description: "La versión clásica de la lotería mexicana de 54 cartas.",
  theme: "tradicional",
  cards: [
    {
      id: 1,
      key: "el-gallo",
      name: "El Gallo",
      image: "/cards/loteria/tradicional/el-gallo.png",
      callout: "El que le cantó a San Pedro no le volverá a cantar.",
    },
    {
      id: 2,
      key: "el-diablo",
      name: "El Diablo",
      image: "/cards/loteria/tradicional/el-diablo.png",
      callout: "Pórtate bien cuatito, si no te lleva el coloradito.",
    },
    {
      id: 3,
      key: "la-dama",
      name: "La Dama",
      image: "/cards/loteria/tradicional/la-dama.png",
      callout: "Puliendo el paso, por toda la calle real.",
    },
    {
      id: 4,
      key: "el-catrin",
      name: "El Catrín",
      image: "/cards/loteria/tradicional/el-catrin.png",
      callout: "Don Ferruco en la alameda, su bastón quería tirar.",
    },
    {
      id: 5,
      key: "el-paraguas",
      name: "El Paraguas",
      image: "/cards/loteria/tradicional/el-paraguas.png",
      callout: "Para el sol y para el agua.",
    },
    {
      id: 6,
      key: "la-sirena",
      name: "La Sirena",
      image: "/cards/loteria/tradicional/la-sirena.png",
      callout: "Con los cantos de sirena no te vayas a marear.",
    },
    {
      id: 7,
      key: "la-escalera",
      name: "La Escalera",
      image: "/cards/loteria/tradicional/la-escalera.png",
      callout: "Súbeme paso a pasito, no quieras pegar brinquitos.",
    },
    {
      id: 8,
      key: "la-botella",
      name: "La Botella",
      image: "/cards/loteria/tradicional/la-botella.png",
      callout: "La herramienta del borracho.",
    },
    {
      id: 9,
      key: "el-barril",
      name: "El Barril",
      image: "/cards/loteria/tradicional/el-barril.png",
      callout: "Tanto bebió el albañil, que quedó como barril.",
    },
    {
      id: 10,
      key: "el-arbol",
      name: "El Árbol",
      image: "/cards/loteria/tradicional/el-arbol.png",
      callout: "El que a buen árbol se arrima, buena sombra le cobija.",
    },
    {
      id: 11,
      key: "el-melon",
      name: "El Melón",
      image: "/cards/loteria/tradicional/el-melon.png",
      callout: "Me lo das o me lo quitas.",
    },
    {
      id: 12,
      key: "el-valiente",
      name: "El Valiente",
      image: "/cards/loteria/tradicional/el-valiente.png",
      callout: "Por qué le corres cobarde, trayendo tan buen puñal.",
    },
    {
      id: 13,
      key: "el-gorrito",
      name: "El Gorrito",
      image: "/cards/loteria/tradicional/el-gorrito.png",
      callout: "Ponle su gorrito al nene, no se nos vaya a resfriar.",
    },
    {
      id: 14,
      key: "la-muerte",
      name: "La Muerte",
      image: "/cards/loteria/tradicional/la-muerte.png",
      callout: "La muerte tilica y flaca.",
    },
    {
      id: 15,
      key: "la-pera",
      name: "La Pera",
      image: "/cards/loteria/tradicional/la-pera.png",
      callout: "El que espera, desespera.",
    },
    {
      id: 16,
      key: "la-bandera",
      name: "La Bandera",
      image: "/cards/loteria/tradicional/la-bandera.png",
      callout: "Verde, blanco y colorado, la bandera del soldado.",
    },
    {
      id: 17,
      key: "el-bandolon",
      name: "El Bandolón",
      image: "/cards/loteria/tradicional/el-bandolon.png",
      callout: "Tocando su bandolón, está el mariachi Simón.",
    },
    {
      id: 18,
      key: "el-violoncello",
      name: "El Violoncello",
      image: "/cards/loteria/tradicional/el-violoncello.png",
      callout: "Creciendo se fue hasta el cielo, y como no fue violín, tuvo que ser violoncello.",
    },
    {
      id: 19,
      key: "la-garza",
      name: "La Garza",
      image: "/cards/loteria/tradicional/la-garza.png",
      callout: "Al otro lado del río tengo mi banco de arena, donde se sienta mi chata pico de garza morena.",
    },
    {
      id: 20,
      key: "el-pajaro",
      name: "El Pájaro",
      image: "/cards/loteria/tradicional/el-pajaro.png",
      callout: "Tú me traes a puros brincos, como pájaro en la rama.",
    },
    {
      id: 21,
      key: "la-mano",
      name: "La Mano",
      image: "/cards/loteria/tradicional/la-mano.png",
      callout: "La mano del escribano.",
    },
    {
      id: 22,
      key: "la-bota",
      name: "La Bota",
      image: "/cards/loteria/tradicional/la-bota.png",
      callout: "Una bota igual que la otra.",
    },
    {
      id: 23,
      key: "la-luna",
      name: "La Luna",
      image: "/cards/loteria/tradicional/la-luna.png",
      callout: "El farol de los enamorados.",
    },
    {
      id: 24,
      key: "el-cotorro",
      name: "El Cotorro",
      image: "/cards/loteria/tradicional/el-cotorro.png",
      callout: "Cotorro, cotorro saca la pata, y empiézame a platicar.",
    },
    {
      id: 25,
      key: "el-borracho",
      name: "El Borracho",
      image: "/cards/loteria/tradicional/el-borracho.png",
      callout: "¡Ay qué borracho tan necio, ya no lo puedo aguantar!",
    },
    {
      id: 26,
      key: "el-negrito",
      name: "El Negrito",
      image: "/cards/loteria/tradicional/el-negrito.png",
      callout: "El que se comió el azúcar.",
    },
    {
      id: 27,
      key: "el-corazon",
      name: "El Corazón",
      image: "/cards/loteria/tradicional/el-corazon.png",
      callout: "No me extrañes corazón, que regreso en el camión.",
    },
    {
      id: 28,
      key: "la-sandia",
      name: "La Sandía",
      image: "/cards/loteria/tradicional/la-sandia.png",
      callout: "La barriga que Juan tenía, era empacho de sandía.",
    },
    {
      id: 29,
      key: "el-tambor",
      name: "El Tambor",
      image: "/cards/loteria/tradicional/el-tambor.png",
      callout: "No te arrugues cuero viejo, que te quiero pa’ tambor.",
    },
    {
      id: 30,
      key: "el-camaron",
      name: "El Camarón",
      image: "/cards/loteria/tradicional/el-camaron.png",
      callout: "Camarón que se duerme se lo lleva la corriente.",
    },
    {
      id: 31,
      key: "las-jaras",
      name: "Las Jaras",
      image: "/cards/loteria/tradicional/las-jaras.png",
      callout: "Las jaras del indio Adán, donde pegan dan.",
    },
    {
      id: 32,
      key: "el-musico",
      name: "El Músico",
      image: "/cards/loteria/tradicional/el-musico.png",
      callout: "El músico trompa de hule, ya no me quiere tocar.",
    },
    {
      id: 33,
      key: "la-arana",
      name: "La Araña",
      image: "/cards/loteria/tradicional/la-arana.png",
      callout: "Atarántamela a palos, no me la dejes llegar.",
    },
    {
      id: 34,
      key: "el-soldado",
      name: "El Soldado",
      image: "/cards/loteria/tradicional/el-soldado.png",
      callout: "Uno, dos y tres, el soldado p’al cuartel.",
    },
    {
      id: 35,
      key: "la-estrella",
      name: "La Estrella",
      image: "/cards/loteria/tradicional/la-estrella.png",
      callout: "La guía de los marineros.",
    },
    {
      id: 36,
      key: "el-cazo",
      name: "El Cazo",
      image: "/cards/loteria/tradicional/el-cazo.png",
      callout: "El caso que te hago es poco.",
    },
    {
      id: 37,
      key: "el-mundo",
      name: "El Mundo",
      image: "/cards/loteria/tradicional/el-mundo.png",
      callout: "Este mundo es una bola, y nosotros un bolón.",
    },
    {
      id: 38,
      key: "el-apache",
      name: "El Apache",
      image: "/cards/loteria/tradicional/el-apache.png",
      callout: "¡Ah chihuahua! cuánto apache con pantalón y huarache.",
    },
    {
      id: 39,
      key: "el-nopal",
      name: "El Nopal",
      image: "/cards/loteria/tradicional/el-nopal.png",
      callout: "Al nopal solo lo van a ver cuando tiene tunas.",
    },
    {
      id: 40,
      key: "el-alacran",
      name: "El Alacrán",
      image: "/cards/loteria/tradicional/el-alacran.png",
      callout: "El que con la cola pica, le dan una paliza.",
    },
    {
      id: 41,
      key: "la-rosa",
      name: "La Rosa",
      image: "/cards/loteria/tradicional/la-rosa.png",
      callout: "Rosita, Rosaura, ven que te quiero ahora.",
    },
    {
      id: 42,
      key: "la-calavera",
      name: "La Calavera",
      image: "/cards/loteria/tradicional/la-calavera.png",
      callout: "Al otro lado de la barranca, hay una calavera blanca.",
    },
    {
      id: 43,
      key: "la-campana",
      name: "La Campana",
      image: "/cards/loteria/tradicional/la-campana.png",
      callout: "Tú con la campana y yo con tu hermana.",
    },
    {
      id: 44,
      key: "el-cantarito",
      name: "El Cantarito",
      image: "/cards/loteria/tradicional/el-cantarito.png",
      callout: "Tanto va el cántaro al agua, hasta que se rompe.",
    },
    {
      id: 45,
      key: "el-venado",
      name: "El Venado",
      image: "/cards/loteria/tradicional/el-venado.png",
      callout: "Saltando va buscando, pero no ve nada.",
    },
    {
      id: 46,
      key: "el-sol",
      name: "El Sol",
      image: "/cards/loteria/tradicional/el-sol.png",
      callout: "La cobija de los pobres.",
    },
    {
      id: 47,
      key: "la-corona",
      name: "La Corona",
      image: "/cards/loteria/tradicional/la-corona.png",
      callout: "El sombrero de los reyes.",
    },
    {
      id: 48,
      key: "la-chalupa",
      name: "La Chalupa",
      image: "/cards/loteria/tradicional/la-chalupa.png",
      callout: "Rema y rema va Lupita, sentada en su chalupita.",
    },
    {
      id: 49,
      key: "el-pino",
      name: "El Pino",
      image: "/cards/loteria/tradicional/el-pino.png",
      callout: "Fresco y oloroso, en todo tiempo hermoso.",
    },
    {
      id: 50,
      key: "el-pescado",
      name: "El Pescado",
      image: "/cards/loteria/tradicional/el-pescado.png",
      callout: "El que por la boca muere, aunque mudo fuere.",
    },
    {
      id: 51,
      key: "la-palma",
      name: "La Palma",
      image: "/cards/loteria/tradicional/la-palma.png",
      callout: "Palmero sube a la palma y bájame un coco real.",
    },
    {
      id: 52,
      key: "la-maceta",
      name: "La Maceta",
      image: "/cards/loteria/tradicional/la-maceta.png",
      callout: "El que nace pa’ maceta, del corredor no pasa.",
    },
    {
      id: 53,
      key: "el-arpa",
      name: "El Arpa",
      image: "/cards/loteria/tradicional/el-arpa.png",
      callout: "Arpa vieja de mi suegra, ya no sirves pa’ tocar.",
    },
    {
      id: 54,
      key: "la-rana",
      name: "La Rana",
      image: "/cards/loteria/tradicional/la-rana.png",
      callout: "Al ver a la verde rana, qué brinco pegó tu hermana.",
    },
  ],
};

export const LOTERIA_DECKS: LoteriaDeckDefinition[] = [
  LOTERIA_TRADICIONAL_DECK,
];

export function getLoteriaDeckBySlug(slug: string) {
  return LOTERIA_DECKS.find((deck) => deck.slug === slug) ?? LOTERIA_TRADICIONAL_DECK;
}
