import type { LoteriaDeckDefinition } from "./loteriaTypes";

export const LOTERIA_TRADICIONAL_DECK: LoteriaDeckDefinition = {
  id: "deck-tradicional",
  slug: "tradicional",
  name: "Lotería Mexicana Tradicional",
  description: "La versión clásica de la lotería mexicana de 54 cartas.",
  theme: "tradicional",
  cards: [
    {
      id: 1,
      key: "el_gallo",
      name: "El Gallo",
      image: "/cards/loteria/tradicional/el_gallo.png",
      callout: "El que le cantó a San Pedro no le volverá a cantar.",
    },
    {
      id: 2,
      key: "el_diablito",
      name: "El Diablito",
      image: "/cards/loteria/tradicional/el_diablito.png",
      callout: "Pórtate bien cuatito, si no te lleva el coloradito.",
    },
    {
      id: 3,
      key: "la_dama",
      name: "La Dama",
      image: "/cards/loteria/tradicional/la_dama.png",
      callout: "Puliendo el paso, por toda la calle real.",
    },
    {
      id: 4,
      key: "el_catrin",
      name: "El Catrín",
      image: "/cards/loteria/tradicional/el_catrin.png",
      callout: "Don Ferruco en la alameda, su bastón quería tirar.",
    },
    {
      id: 5,
      key: "el_paraguas",
      name: "El Paraguas",
      image: "/cards/loteria/tradicional/el_paraguas.png",
      callout: "Para el sol y para el agua.",
    },
    {
      id: 6,
      key: "la_sirena",
      name: "La Sirena",
      image: "/cards/loteria/tradicional/la_sirena.png",
      callout: "Con los cantos de sirena no te vayas a marear.",
    },
    {
      id: 7,
      key: "la_escalera",
      name: "La Escalera",
      image: "/cards/loteria/tradicional/la_escalera.png",
      callout: "Súbeme paso a pasito, no quieras pegar brinquitos.",
    },
    {
      id: 8,
      key: "la_botella",
      name: "La Botella",
      image: "/cards/loteria/tradicional/la_botella.png",
      callout: "La herramienta del borracho.",
    },
    {
      id: 9,
      key: "el_barril",
      name: "El Barril",
      image: "/cards/loteria/tradicional/el_barril.png",
      callout: "Tanto bebió el albañil, que quedó como barril.",
    },
    {
      id: 10,
      key: "el_arbol",
      name: "El Árbol",
      image: "/cards/loteria/tradicional/el_arbol.png",
      callout: "El que a buen árbol se arrima, buena sombra le cobija.",
    },
    {
      id: 11,
      key: "el_melon",
      name: "El Melón",
      image: "/cards/loteria/tradicional/el_melon.png",
      callout: "Me lo das o me lo quitas.",
    },
    {
      id: 12,
      key: "el_valiente",
      name: "El Valiente",
      image: "/cards/loteria/tradicional/el_valiente.png",
      callout: "Por qué le corres cobarde, trayendo tan buen puñal.",
    },
    {
      id: 13,
      key: "el_gorrito",
      name: "El Gorrito",
      image: "/cards/loteria/tradicional/el_gorrito.png",
      callout: "Ponle su gorrito al nene, no se nos vaya a resfriar.",
    },
    {
      id: 14,
      key: "la_muerte",
      name: "La Muerte",
      image: "/cards/loteria/tradicional/la_muerte.png",
      callout: "La muerte tilica y flaca.",
    },
    {
      id: 15,
      key: "la_pera",
      name: "La Pera",
      image: "/cards/loteria/tradicional/la_pera.png",
      callout: "El que espera, desespera.",
    },
    {
      id: 16,
      key: "la_bandera",
      name: "La Bandera",
      image: "/cards/loteria/tradicional/la_bandera.png",
      callout: "Verde, blanco y colorado, la bandera del soldado.",
    },
    {
      id: 17,
      key: "el_bandolon",
      name: "El Bandolón",
      image: "/cards/loteria/tradicional/el_bandolon.png",
      callout: "Tocando su bandolón, está el mariachi Simón.",
    },
    {
      id: 18,
      key: "el_violoncello",
      name: "El Violoncello",
      image: "/cards/loteria/tradicional/el_violoncello.png",
      callout: "Creciendo se fue hasta el cielo, y como no fue violín, tuvo que ser violoncello.",
    },
    {
      id: 19,
      key: "la_garza",
      name: "La Garza",
      image: "/cards/loteria/tradicional/la_garza.png",
      callout: "Al otro lado del río tengo mi banco de arena, donde se sienta mi chata pico de garza morena.",
    },
    {
      id: 20,
      key: "el_pajaro",
      name: "El Pájaro",
      image: "/cards/loteria/tradicional/el_pajaro.png",
      callout: "Tú me traes a puros brincos, como pájaro en la rama.",
    },
    {
      id: 21,
      key: "la_mano",
      name: "La Mano",
      image: "/cards/loteria/tradicional/la_mano.png",
      callout: "La mano del escribano.",
    },
    {
      id: 22,
      key: "la_bota",
      name: "La Bota",
      image: "/cards/loteria/tradicional/la_bota.png",
      callout: "Una bota igual que la otra.",
    },
    {
      id: 23,
      key: "la_luna",
      name: "La Luna",
      image: "/cards/loteria/tradicional/la_luna.png",
      callout: "El farol de los enamorados.",
    },
    {
      id: 24,
      key: "el_cotorro",
      name: "El Cotorro",
      image: "/cards/loteria/tradicional/el_cotorro.png",
      callout: "Cotorro, cotorro saca la pata, y empiézame a platicar.",
    },
    {
      id: 25,
      key: "el_borracho",
      name: "El Borracho",
      image: "/cards/loteria/tradicional/el_borracho.png",
      callout: "¡Ay qué borracho tan necio, ya no lo puedo aguantar!",
    },
    {
      id: 26,
      key: "el_negrito",
      name: "El Negrito",
      image: "/cards/loteria/tradicional/el_negrito.png",
      callout: "El que se comió el azúcar.",
    },
    {
      id: 27,
      key: "el_corazon",
      name: "El Corazón",
      image: "/cards/loteria/tradicional/el_corazon.png",
      callout: "No me extrañes corazón, que regreso en el camión.",
    },
    {
      id: 28,
      key: "la_sandia",
      name: "La Sandía",
      image: "/cards/loteria/tradicional/la_sandia.png",
      callout: "La barriga que Juan tenía, era empacho de sandía.",
    },
    {
      id: 29,
      key: "el_tambor",
      name: "El Tambor",
      image: "/cards/loteria/tradicional/el_tambor.png",
      callout: "No te arrugues cuero viejo, que te quiero pa’ tambor.",
    },
    {
      id: 30,
      key: "el_camaron",
      name: "El Camarón",
      image: "/cards/loteria/tradicional/el_camaron.png",
      callout: "Camarón que se duerme se lo lleva la corriente.",
    },
    {
      id: 31,
      key: "las_jaras",
      name: "Las Jaras",
      image: "/cards/loteria/tradicional/las_jaras.png",
      callout: "Las jaras del indio Adán, donde pegan dan.",
    },
    {
      id: 32,
      key: "el_musico",
      name: "El Músico",
      image: "/cards/loteria/tradicional/el_musico.png",
      callout: "El músico trompa de hule, ya no me quiere tocar.",
    },
    {
      id: 33,
      key: "la_arana",
      name: "La Araña",
      image: "/cards/loteria/tradicional/la_arana.png",
      callout: "Atarántamela a palos, no me la dejes llegar.",
    },
    {
      id: 34,
      key: "el_soldado",
      name: "El Soldado",
      image: "/cards/loteria/tradicional/el_soldado.png",
      callout: "Uno, dos y tres, el soldado p’al cuartel.",
    },
    {
      id: 35,
      key: "la_estrella",
      name: "La Estrella",
      image: "/cards/loteria/tradicional/la_estrella.png",
      callout: "La guía de los marineros.",
    },
    {
      id: 36,
      key: "el_cazo",
      name: "El Cazo",
      image: "/cards/loteria/tradicional/el_cazo.png",
      callout: "El caso que te hago es poco.",
    },
    {
      id: 37,
      key: "el_mundo",
      name: "El Mundo",
      image: "/cards/loteria/tradicional/el_mundo.png",
      callout: "Este mundo es una bola, y nosotros un bolón.",
    },
    {
      id: 38,
      key: "el_apache",
      name: "El Apache",
      image: "/cards/loteria/tradicional/el_apache.png",
      callout: "¡Ah chihuahua! cuánto apache con pantalón y huarache.",
    },
    {
      id: 39,
      key: "el_nopal",
      name: "El Nopal",
      image: "/cards/loteria/tradicional/el_nopal.png",
      callout: "Al nopal solo lo van a ver cuando tiene tunas.",
    },
    {
      id: 40,
      key: "el_alacran",
      name: "El Alacrán",
      image: "/cards/loteria/tradicional/el_alacran.png",
      callout: "El que con la cola pica, le dan una paliza.",
    },
    {
      id: 41,
      key: "la_rosa",
      name: "La Rosa",
      image: "/cards/loteria/tradicional/la_rosa.png",
      callout: "Rosita, Rosaura, ven que te quiero ahora.",
    },
    {
      id: 42,
      key: "la_calavera",
      name: "La Calavera",
      image: "/cards/loteria/tradicional/la_calavera.png",
      callout: "Al otro lado de la barranca, hay una calavera blanca.",
    },
    {
      id: 43,
      key: "la_campana",
      name: "La Campana",
      image: "/cards/loteria/tradicional/la_campana.png",
      callout: "Tú con la campana y yo con tu hermana.",
    },
    {
      id: 44,
      key: "el_cantarito",
      name: "El Cantarito",
      image: "/cards/loteria/tradicional/el_cantarito.png",
      callout: "Tanto va el cántaro al agua, hasta que se rompe.",
    },
    {
      id: 45,
      key: "el_venado",
      name: "El Venado",
      image: "/cards/loteria/tradicional/el_venado.png",
      callout: "Saltando va buscando, pero no ve nada.",
    },
    {
      id: 46,
      key: "el_sol",
      name: "El Sol",
      image: "/cards/loteria/tradicional/el_sol.png",
      callout: "La cobija de los pobres.",
    },
    {
      id: 47,
      key: "la_corona",
      name: "La Corona",
      image: "/cards/loteria/tradicional/la_corona.png",
      callout: "El sombrero de los reyes.",
    },
    {
      id: 48,
      key: "la_chalupa",
      name: "La Chalupa",
      image: "/cards/loteria/tradicional/la_chalupa.png",
      callout: "Rema y rema va Lupita, sentada en su chalupita.",
    },
    {
      id: 49,
      key: "el_pino",
      name: "El Pino",
      image: "/cards/loteria/tradicional/el_pino.png",
      callout: "Fresco y oloroso, en todo tiempo hermoso.",
    },
    {
      id: 50,
      key: "el_pescado",
      name: "El Pescado",
      image: "/cards/loteria/tradicional/el_pescado.png",
      callout: "El que por la boca muere, aunque mudo fuere.",
    },
    {
      id: 51,
      key: "la_palma",
      name: "La Palma",
      image: "/cards/loteria/tradicional/la_palma.png",
      callout: "Palmero sube a la palma y bájame un coco real.",
    },
    {
      id: 52,
      key: "la_maceta",
      name: "La Maceta",
      image: "/cards/loteria/tradicional/la_maceta.png",
      callout: "El que nace pa’ maceta, del corredor no pasa.",
    },
    {
      id: 53,
      key: "el_arpa",
      name: "El Arpa",
      image: "/cards/loteria/tradicional/el_arpa.png",
      callout: "Arpa vieja de mi suegra, ya no sirves pa’ tocar.",
    },
    {
      id: 54,
      key: "la_rana",
      name: "La Rana",
      image: "/cards/loteria/tradicional/la_rana.png",
      callout: "Al ver a la verde rana, qué brinco pegó tu hermana.",
    },
  ],
};

export const LOTERIA_DECKS: LoteriaDeckDefinition[] = [
  LOTERIA_TRADICIONAL_DECK,
];

export function getLoteriaDeckBySlug(slug: string) {
  return LOTERIA_DECKS.find((deck) => deck.slug === slug) ?? LOTERIA_TRADICIONAL_DECK;
}
